# Generated by Django 3.1.7 on 2021-05-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerakiApp', '0002_auto_20210523_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        
    ]
