# Generated by Django 3.1.7 on 2021-05-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MerakiApp', '0004_auto_20210523_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
