# Generated by Django 3.1.7 on 2021-05-24 08:22

import MerakiApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerakiApp', '0005_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=MerakiApp.models.create_id, max_length=200),
        ),
    ]
