# Generated by Django 3.1.7 on 2021-05-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MerakiApp', '0007_auto_20210524_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
