# Generated by Django 3.1.7 on 2021-05-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MerakiApp', '0009_shipping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
