# Generated by Django 3.1.7 on 2021-05-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerakiApp', '0017_auto_20210524_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentmethod',
            field=models.CharField(blank=True, choices=[('COD', 'COD'), ('ESEWA', 'ESEWA'), ('BANK TRANSFER', 'BANKTRANSFER'), ('FONEPAY', 'FONEPAY')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentstatus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
