# Generated by Django 3.1.7 on 2021-05-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerakiApp', '0019_order_specialinstructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Order Placed', 'Order Placed'), ('Acknowledged', 'Acknowledged'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
