# Generated by Django 3.1.7 on 2021-05-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerakiApp', '0020_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expectedarrival',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
