# Generated by Django 3.1.7 on 2021-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerakiApp', '0022_auto_20210525_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expectedarrival',
            field=models.DateField(null=True),
        ),
    ]
