# Generated by Django 3.1.7 on 2021-05-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerakiApp', '0024_auto_20210525_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expectedarrival',
            field=models.DateField(null=True),
        ),
    ]
