# Generated by Django 3.1.7 on 2021-05-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerakiApp', '0025_auto_20210525_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordertotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
