# Generated by Django 3.1.7 on 2021-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerakiApp', '0038_auto_20210528_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage_slider',
            name='Page',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=3, primary_key=True, serialize=False),
        ),
    ]
